[package]
name = "particle-life-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.1"
env_logger = "0.10.0"
log = "0.4.17"
vulkano = "0.32.3"
